export const GET_ADMIN_PROFILE = 'GET_ADMIN_PROFILE';
export const ADMIN_PROFILE_SUCCESS = 'ADMIN_PROFILE_SUCCESS';
export const ADMIN_PROFILE_ERROR = 'ADMIN_PROFILE_ERROR';

export const UPDATE_ADMIN_PROFILE_IMAGE_SUCCESS =
  'UPDATE_ADMIN_PROFILE_IMAGE_SUCCESS';

export const UPDATE_ADMIN_PROFILE_SUCCESS = 'UPDATE_ADMIN_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PASSWORD_SUCCESS = 'UPDATE_USER_PASSWORD_SUCCESS';

export const GET_CITIES = 'GET_CITIES';
export const CITIES_SUCCESS = 'CITIES_SUCCESS';
export const CITIES_ERROR = 'CITIES_ERROR';
