export const CLEAR_MY_ORGANIZATION_COURSES = 'CLEAR_MY_ORGANIZATION_COURSES';
export const MY_ORGANIZATION_COURSES = 'MY_ORGANIZATION_COURSES';
export const MY_ORGANIZATION_COURSES_SUCCESS =
  'MY_ORGANIZATION_COURSES_SUCCESS';
export const MY_ORGANIZATION_COURSES_ERROR = 'MY_ORGANIZATION_COURSES_ERROR';

export const ENROLL_COURSE = 'ENROLL_COURSE';
export const ENROLL_COURSE_SUCCESS = 'ENROLL_COURSE_SUCCESS';
export const ENROLL_COURSE_ERROR = 'ENROLL_COURSE_ERROR';

export const CLEAR_COURSE = 'CLEAR_COURSE';
export const GET_COURSE = 'GET_COURSE';
export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS';
export const GET_COURSE_ERROR = 'GET_COURSE_ERROR';

export const CLEAR_COURSE_NOTES = 'CLEAR_COURSE_NOTES';
export const GET_COURSE_NOTES = 'GET_COURSE_NOTES';
export const GET_COURSE_NOTES_SUCCESS = 'GET_COURSE_NOTES_SUCCESS';
export const GET_COURSE_NOTES_ERROR = 'GET_COURSE_NOTES_ERROR';

export const GET_LESSON_NOTES_SUCCESS = 'GET_LESSON_NOTES_SUCCESS';
export const DELETE_LESSON_NOTES_SUCCESS = 'DELETE_LESSON_NOTES_SUCCESS';
export const ADD_LESSON_NOTES_SUCCESS = 'ADD_LESSON_NOTES_SUCCESS';
export const UPDATE_LESSON_NOTES_SUCCESS = 'UPDATE_LESSON_NOTES_SUCCESS';
export const CLEAR_LESSON_NOTES = 'CLEAR_LESSON_NOTES';

export const DELETE_COURSE_NOTES_SUCCESS = 'DELETE_COURSE_NOTES_SUCCESS';
export const UPDATE_COURSE_NOTES_SUCCESS = 'UPDATE_COURSE_NOTES_SUCCESS';

export const SET_CURRENT_LESSON = 'SET_CURRENT_LESSON';
export const UPDATE_CURRENT_LESSON_MILESTONES =
  'UPDATE_CURRENT_LESSON_MILESTONES';

export const SAVE_LESSON_SUCCESS = 'SAVE_LESSON_SUCCESS';
export const UNDOSAVED_LESSON_SUCCESS = 'UNDOSAVED_LESSON_SUCCESS';

export const CLEAR_COURSE_BOOKMARKS = 'CLEAR_COURSE_BOOKMARKS';
export const GET_COURSE_BOOKMARKS = 'GET_COURSE_BOOKMARKS';
export const GET_COURSE_BOOKMARKS_SUCCESS = 'GET_COURSE_BOOKMARKS_SUCCESS';
export const GET_COURSE_BOOKMARKS_ERROR = 'GET_COURSE_BOOKMARKS_ERROR';

export const GET_COURSE_SYLLABUS = 'GET_COURSE_SYLLABUS';
export const GET_COURSE_SYLLABUS_SUCCESS = 'GET_COURSE_SYLLABUS_SUCCESS';
export const GET_COURSE_SYLLABUS_ERROR = 'GET_COURSE_SYLLABUS_ERROR';

export const GET_COURSE_REVIEWS = 'GET_COURSE_REVIEWS';
export const GET_COURSE_REVIEWS_SUCCESS = 'GET_COURSE_REVIEWS_SUCCESS';
export const GET_COURSE_REVIEWS_ERROR = 'GET_COURSE_REVIEWS_ERROR';

export const TOGGLE_COURSE_NOTES_POPUP = 'TOGGLE_COURSE_NOTES_POPUP';

export const UPDATE_VIEW_COUNT = 'UPDATE_VIEW_COUNT';

export const GET_SAVED_LESSONS = 'GET_SAVED_LESSONS';
export const SAVED_LESSONS_SUCCESS = 'SAVED_LESSONS_SUCCESS';
export const SAVED_LESSONS_ERROR = 'SAVED_LESSONS_ERROR';

export const UPDATE_QUIZ_COMPLETION = 'UPDATE_QUIZ_COMPLETION';
