export const FETCH_CONSOLE_REQUESTED = 'FETCH_CONSOLE_REQUESTED';
export const FETCH_CONSOLE_SUCCEEDED = 'FETCH_CONSOLE_SUCCEEDED';
export const FETCH_CONSOLE_FAILED = 'FETCH_CONSOLE_FAILED';

export const DISCARD_CONSOLE_REQUESTED = 'DISCARD_CONSOLE_REQUESTED';
export const DISCARD_CONSOLE_SUCCEEDED = 'DISCARD_CONSOLE_SUCCEEDED';
export const DISCARD_CONSOLE_FAILED = 'DISCARD_CONSOLE_FAILED';

export const FETCH_NOTEBOOK_REQUESTED = 'FETCH_NOTEBOOK_REQUESTED';
export const FETCH_NOTEBOOK_SUCCEEDED = 'FETCH_NOTEBOOK_SUCCEEDED';
export const FETCH_NOTEBOOK_FAILED = 'FETCH_NOTEBOOK_FAILED';

export const DISCARD_NOTEBOOK_REQUESTED = 'DISCARD_NOTEBOOK_REQUESTED';
export const DISCARD_NOTEBOOK_SUCCEEDED = 'DISCARD_NOTEBOOK_SUCCEEDED';
export const DISCARD_NOTEBOOK_FAILED = 'DISCARD_NOTEBOOK_FAILED';

export const UNSET_CONSOLE_URL = 'UNSET_CONSOLE_URL';
