export const FETCH_CASE_REQUESTED = "FETCH_CASE_REQUESTED";
export const FETCH_CASE_SUCCEEDED = "FETCH_CASE_SUCCEEDED";
export const FETCH_CASE_FAILED = "FETCH_CASE_FAILED";

export const SINGLE_MILESTONE_DATA_REQUESTED = "SINGLE_MILESTONE_DATA_REQUESTED";
export const SINGLE_MILESTONE_DATA_SUCCEEDED = "SINGLE_MILESTONE_DATA_SUCCEEDED";
export const SINGLE_MILESTONE_DATA_FAILED = "SINGLE_MILESTONE_DATA_FAILED";

export const COMPARE_STEPS_REQUESTED = "COMPARE_STEPS_REQUESTED";
export const COMPARE_STEPS_SUCCEEDED = "COMPARE_STEPS_SUCCEEDED";
export const COMPARE_STEPS_FAILED = "COMPARE_STEPS_FAILED";

export const MODE_DATA_REQUESTED = "MODE_DATA_REQUESTED";
export const MODE_DATA_SUCCEEDED = "MODE_DATA_SUCCEEDED";
export const MODE_DATA_FAILED = "MODE_DATA_FAILED";

export const MODE_OUTPUT_REQUESTED = "MODE_OUTPUT_REQUESTED";
export const MODE_OUTPUT_SUCCEEDED = "MODE_OUTPUT_SUCCEEDED";
export const MODE_OUTPUT_FAILED = "MODE_OUTPUT_FAILED";

export const GET_SUBMIT_OUTPUT_REQUESTED = "GET_SUBMIT_OUTPUT_REQUESTED";
export const GET_SUBMIT_OUTPUT_SUCCEEDED = "GET_SUBMIT_OUTPUT_SUCCEEDED";
export const GET_SUBMIT_OUTPUT_FAILED = "GET_SUBMIT_OUTPUT_FAILED";

export const GET_SUBMIT_ALL_REQUESTED = "GET_SUBMIT_ALL_REQUESTED";
export const GET_SUBMIT_ALL_SUCCEEDED = "GET_SUBMIT_ALL_SUCCEEDED";
export const GET_SUBMIT_ALL_FAILED = "GET_SUBMIT_ALL_FAILED";

export const GET_DATA_DICTIONARY_SUCCEEDED = "GET_DATA_DICTIONARY_SUCCEEDED";

export const GET_DATA_PREVIEW_SUCCEEDED = "GET_DATA_PREVIEW_SUCCEEDED";

export const ON_CONSOLE_EDITOR_DATA_CHANGE = "ON_CONSOLE_EDITOR_DATA_CHANGE";

export const CURRENT_VALUE = "CURRENT_VALUE";

export const UPDATED_MODE = "UPDATED_MODE";

export const IS_SUBMIT_LOADING = "IS_SUBMIT_LOADING";

export const IS_SUBMIT_SUCCESS = "IS_SUBMIT_SUCCESS";

export const IS_SHOW_CODE = "IS_SHOW_CODE";

export const IS_RESET_CLICKED = "IS_RESET_CLICKED";

export const UPDATE_USER_ID = "UPDATE_USER_ID";

export const UPDATE_CASE_ID = "UPDATE_CASE_ID";

export const OPEN_RESULT_EXPAND_MODAL = "OPEN_RESULT_EXPAND_MODAL";

export const OPEN_COMPARE_STEPS_MODAL = "OPEN_COMPARE_STEPS_MODAL";