export const SELECT_MILESTONE = 'SELECT_MILESTONE';
export const RESET_SELECT_MILESTONE = 'RESET_SELECT_MILESTONE';
export const RESET_COMPARE_STEP = 'RESET_COMPARE_STEP';

export const SELECT_REFERENCE_STEP = 'SELECT_REFERENCE_STEP';
export const SELECT_USER_STEP = 'SELECT_USER_STEP';

export const FETCH_COMPARE_REQUESTED = 'FETCH_COMPARE_REQUESTED';
export const FETCH_COMPARE_SUCCEEDED = 'FETCH_COMPARE_SUCCEEDED';
export const FETCH_COMPARE_FAILED = 'FETCH_COMPARE_FAILED';

export const FETCH_REFERENCE_STEP_REQUESTED = 'FETCH_REFERENCE_STEP_REQUESTED';
export const FETCH_REFERENCE_STEP_SUCCEEDED = 'FETCH_REFERENCE_STEP_SUCCEEDED';
export const FETCH_REFERENCE_STEP_FAILED = 'FETCH_REFERENCE_STEP_FAILED';
