export const GET_FUNCTIONS_CATEGORIES = 'GET_FUNCTIONS_CATEGORIES';
export const GET_FUNCTIONS_CATEGORIES_SUCCESS =
  'GET_FUNCTIONS_CATEGORIES_SUCCESS';
export const GET_FUNCTIONS_CATEGORIES_ERROR = 'GET_FUNCTIONS_CATEGORIES_ERROR';

export const GET_FUNCTIONS = 'GET_FUNCTIONS';
export const GET_FUNCTIONS_SUCCESS = 'GET_FUNCTIONS_SUCCESS';
export const GET_FUNCTIONS_ERROR = 'GET_FUNCTIONS_ERROR';

export const FETCH_FUNCTION_SUGGESTIONS_REQUESTED =
  'FETCH_FUNCTION_SUGGESTIONS_REQUESTED';
export const FETCH_FUNCTION_SUGGESTIONS_SUCCEEDED =
  'FETCH_FUNCTION_SUGGESTIONS_SUCCEEDED';
export const FETCH_FUNCTION_SUGGESTIONS_FAILED =
  'FETCH_FUNCTION_SUGGESTIONS_FAILED';

export const PUBLISH_UDF_FUNCTION_REQUESTED = 'PUBLISH_UDF_FUNCTION_REQUESTED';
export const PUBLISH_UDF_FUNCTION_SUCCEEDED = 'PUBLISH_UDF_FUNCTION_SUCCEEDED';
export const PUBLISH_UDF_FUNCTION_FAILED = 'PUBLISH_UDF_FUNCTION_FAILED';

export const UN_PUBLISH_UDF_FUNCTION_REQUESTED =
  'UN_PUBLISH_UDF_FUNCTION_REQUESTED';
export const UN_PUBLISH_UDF_FUNCTION_SUCCEEDED =
  'UN_PUBLISH_UDF_FUNCTION_SUCCEEDED';
export const UN_PUBLISH_UDF_FUNCTION_FAILED = 'UN_PUBLISH_UDF_FUNCTION_FAILED';

export const FETCH_FUNCTION_DESCRIPTION_REQUESTED =
  'FETCH_FUNCTION_DESCRIPTION_REQUESTED';
export const FETCH_FUNCTION_DESCRIPTION_SUCCEEDED =
  'FETCH_FUNCTION_DESCRIPTION_SUCCEEDED';
export const FETCH_FUNCTION_DESCRIPTION_FAILED =
  'FETCH_FUNCTION_DESCRIPTION_FAILED';

export const FETCH_FUNCTION_PARAMETERS_REQUESTED =
  'FETCH_FUNCTION_PARAMETERS_REQUESTED';
export const FETCH_FUNCTION_PARAMETERS_SUCCEEDED =
  'FETCH_FUNCTION_PARAMETERS_SUCCEEDED';
export const FETCH_FUNCTION_PARAMETERS_FAILED =
  'FETCH_FUNCTION_PARAMETERS_FAILED';

export const SET_COLUMN_SELECTION = 'SET_COLUMN_SELECTION';
export const UNSET_COLUMN_SELECTION = 'UNSET_COLUMN_SELECTION';

export const REMOVE_SELECTION = 'REMOVE_SELECTION';

export const SET_CURRENT_FUNCTION = 'SET_CURRENT_FUNCTION';
export const UNSET_CURRENT_FUNCTION = 'UNSET_CURRENT_FUNCTION';

export const SET_PARAMETER_FLYOUT = 'SET_PARAMETER_FLYOUT';
export const UNSET_PARAMETER_FLYOUT = 'UNSET_PARAMETER_FLYOUT';

export const SET_PRO_DETAILS_FLYOUT = 'SET_PRO_DETAILS_FLYOUT';
export const UNSET_PRO_DETAILS_FLYOUT = 'UNSET_PRO_DETAILS_FLYOUT';

export const SET_CURRENT_FUNCTION_CATEGORY = 'SET_CURRENT_FUNCTION_CATEGORY';
export const UNSET_CURRENT_FUNCTION_CATEGORY =
  'UNSET_CURRENT_FUNCTION_CATEGORY';

export const SET_FUNCTION_PARAMETERS = 'SET_FUNCTION_PARAMETERS';
export const UNSET_FUNCTION_PARAMETERS = 'UNSET_FUNCTION_PARAMETERS';

export const UNSET_FUNCTION_DESCRIPTION = 'UNSET_FUNCTION_DESCRIPTION';

export const FUNCTION_EXECUTION_REQUESTED = 'FUNCTION_EXECUTION_REQUESTED';
export const FUNCTION_EXECUTION_SUCCEEDED = 'FUNCTION_EXECUTION_SUCCEEDED';
export const FUNCTION_EXECUTION_FAILED = 'FUNCTION_EXECUTION_FAILED';

export const RESET_FUNCTION_EXECUTION = 'RESET_FUNCTION_EXECUTION';

export const RENAME_UDF_REQUESTED = 'RENAME_UDF_REQUESTED';
export const RENAME_UDF_SUCCEEDED = 'RENAME_UDF_SUCCEEDED';
export const RENAME_UDF_FAILED = 'RENAME_UDF_FAILED';

export const DELETE_UDF_REQUESTED = 'DELETE_UDF_REQUESTED';
export const DELETE_UDF_SUCCEEDED = 'DELETE_UDF_SUCCEEDED';
export const DELETE_UDF_FAILED = 'DELETE_UDF_FAILED';
