export const GET_WHERE_YOU_LEFT = 'GET_WHERE_YOU_LEFT';
export const WHERE_YOU_LEFT_SUCCESS = 'WHERE_YOU_LEFT_SUCCESS';
export const WHERE_YOU_LEFT_ERROR = 'WHERE_YOU_LEFT_ERROR';

export const GET_MY_PROJECTS = 'GET_MY_PROJECTS';
export const MY_PROJECTS_SUCCESS = 'MY_PROJECTS_SUCCESS';
export const MY_PROJECTS_ERROR = 'MY_PROJECTS_ERROR';

export const GET_DASHBOARD_ALL_NOTES = 'GET_DASHBOARD_ALL_NOTES';
export const DASHBOARD_ALL_NOTES_SUCCESS = 'DASHBOARD_ALL_NOTES_SUCCESS';
export const DASHBOARD_ALL_NOTES_ERROR = 'DASHBOARD_ALL_NOTES_ERROR';

export const GET_DASHBOARD_ALL_LESSONS = 'GET_DASHBOARD_ALL_LESSONS';
export const DASHBOARD_ALL_LESSONS_SUCCESS = 'DASHBOARD_ALL_LESSONS_SUCCESS';
export const DASHBOARD_ALL_LESSONS_ERROR = 'DASHBOARD_ALL_LESSONS_ERROR';

export const SET_DASHBOARD_LESSON_FILTER = 'SET_DASHBOARD_LESSON_FILTER';
export const SET_DASHBOARD_NOTE_FILTER = 'SET_DASHBOARD_NOTE_FILTER';

export const GET_DASHBOARD_HOME_NOTES = 'GET_DASHBOARD_HOME_NOTES';
export const DASHBOARD_HOME_NOTES_SUCCESS = 'DASHBOARD_HOME_NOTES_SUCCESS';
export const DASHBOARD_HOME_NOTES_ERROR = 'DASHBOARD_HOME_NOTES_ERROR';

export const GET_DASHBOARD_HOME_LESSONS = 'GET_DASHBOARD_HOME_LESSONS';
export const DASHBOARD_HOME_LESSONS_SUCCESS = 'DASHBOARD_HOME_LESSONS_SUCCESS';
export const DASHBOARD_HOME_LESSONS_ERROR = 'DASHBOARD_HOME_LESSONS_ERROR';
