export const SEND_COLLABORATION_INVITE_REQUESTED =
  'SEND_COLLABORATION_INVITE_REQUESTED';
export const SEND_COLLABORATION_INVITE_SUCCEEDED =
  'SEND_COLLABORATION_INVITE_SUCCEEDED';
export const SEND_COLLABORATION_INVITE_FAILED =
  'SEND_COLLABORATION_INVITE_FAILED';

export const FETCH_USER_REQUESTED = 'FETCH_USER_REQUESTED';
export const FETCH_USER_SUCCEEDED = 'FETCH_USER_SUCCEEDED';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';
