export const CLEAR_LOGIN = 'CLEAR_LOGIN';
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const USER_LOGOUT = 'USER_LOGOUT';
export const IS_LOGGED_IN = 'IS_LOGGED_IN';
export const RESET_REGISTER = 'RESET_REGISTER';

export const CLEAR_FORGOT_PASSWORD = 'CLEAR_FORGOT_PASSWORD';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';

export const MY_PROFILE = 'MY_PROFILE';
export const MY_PROFILE_SUCCESS = 'MY_PROFILE_SUCCESS';
export const MY_PROFILE_ERROR = 'MY_PROFILE_ERROR';

export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const FETCH_CAPTCHA = 'FETCH_CAPTCHA';
export const FETCH_CAPTCHA_SUCCESS = 'FETCH_CAPTCHA_SUCCESS';
export const FETCH_CAPTCHA_ERROR = 'FETCH_CAPTCHA_ERROR';

export const RESEND_EMAIL = 'RESEND_EMAIL';
export const RESEND_EMAIL_SUCCESS = 'RESEND_EMAIL_SUCCESS';
export const RESEND_EMAIL_ERROR = 'RESEND_EMAIL_ERROR';

export const SET_EMAIL = 'SET_EMAIL';

export const DISABLE_RESEND_BUTTON = 'DISABLE_RESEND_BUTTON';
