export const GET_ROSTER_USERS = 'GET_ROSTER_USERS';
export const ROSTER_USERS_SUCCESS = 'ROSTER_USERS_SUCCESS';
export const ROSTER_USERS_ERROR = 'ROSTER_USERS_ERROR';

export const GET_ROSTER_ACCESS_LEVELS = 'GET_ROSTER_ACCESS_LEVELS';
export const ROSTER_ACCESS_LEVELS_SUCCESS = 'ROSTER_ACCESS_LEVELS_SUCCESS';
export const ROSTER_ACCESS_LEVELS_ERROR = 'ROSTER_ACCESS_LEVELS_ERROR';

export const GET_ROSTER_DESIGNATIONS = 'GET_ROSTER_DESIGNATIONS';
export const ROSTER_DESIGNATIONS_SUCCESS = 'ROSTER_DESIGNATIONS_SUCCESS';
export const ROSTER_DESIGNATIONS_ERROR = 'ROSTER_DESIGNATIONS_ERROR';

export const GET_ROSTER_RESOURCES = 'GET_ROSTER_RESOURCES';
export const ROSTER_RESOURCES_SUCCESS = 'ROSTER_RESOURCES_SUCCESS';
export const ROSTER_RESOURCES_ERROR = 'ROSTER_RESOURCES_ERROR';

export const SET_ROSTER_FILTER = 'SET_ROSTER_FILTER';
export const SET_ROSTER_PAGINATION = 'SET_ROSTER_PAGINATION';
export const SET_ROSTER_USER = 'SET_ROSTER_USER';

export const DELETE_ROSTER_USER = 'DELETE_ROSTER_USER';
export const CHANGE_ROSTER_USER_TOGGLE = 'CHANGE_ROSTER_USER_TOGGLE';
export const CHANGE_ROSTER_USER_TOGGLE_ERROR =
  'CHANGE_ROSTER_USER_TOGGLE_ERROR';

export const UPDATE_ROSTER_USER_SUCCESS = 'UPDATE_ROSTER_USER_SUCCESS';
export const CREATE_ROSTER_USER_SUCCESS = 'CREATE_ROSTER_USER_SUCCESS';
