export const CLEAR_MY_ORGANIZATION_TRACKS = 'CLEAR_MY_ORGANIZATION_TRACKS';
export const MY_ORGANIZATION_TRACKS = 'MY_ORGANIZATION_TRACKS';
export const MY_ORGANIZATION_TRACKS_SUCCESS = 'MY_ORGANIZATION_TRACKS_SUCCESS';
export const MY_ORGANIZATION_TRACKS_ERROR = 'MY_ORGANIZATION_TRACKS_ERROR';

export const ENROLL_TRACK = 'ENROLL_TRACK';
export const ENROLL_TRACK_SUCCESS = 'ENROLL_TRACK_SUCCESS';
export const ENROLL_TRACK_ERROR = 'ENROLL_TRACK_ERROR';

export const UN_ENROLL_TRACK = 'UN_ENROLL_TRACK';
export const UN_ENROLL_TRACK_SUCCESS = 'UN_ENROLL_TRACK_SUCCESS';
export const UN_ENROLL_TRACK_ERROR = 'UN_ENROLL_TRACK_ERROR';

export const CLEAR_TRACK = 'CLEAR_TRACK';
export const GET_TRACK = 'GET_TRACK';
export const GET_TRACK_SUCCESS = 'GET_TRACK_SUCCESS';
export const GET_TRACK_ERROR = 'GET_TRACK_ERROR';

export const GET_TRACK_COURSE = 'GET_TRACK_COURSE';
export const GET_TRACK_COURSE_SUCCESS = 'GET_TRACK_COURSE_SUCCESS';
export const GET_TRACK_COURSE_ERROR = 'GET_TRACK_COURSE_ERROR';

export const GET_TRACK_REVIEWS = 'GET_TRACK_REVIEWS';
export const GET_TRACK_REVIEWS_SUCCESS = 'GET_TRACK_REVIEWS_SUCCESS';
export const GET_TRACK_REVIEWS_ERROR = 'GET_TRACK_REVIEWS_ERROR';
