export const GET_PERFORMANCE_METRICS = 'GET_PERFORMANCE_METRICS';
export const PERFORMANCE_METRICS_SUCCESS = 'PERFORMANCE_METRICS_SUCCESS';
export const PERFORMANCE_METRICS_ERROR = 'PERFORMANCE_METRICS_ERROR';

export const GET_DASHBOARD_PERFORMANCE_DATA = 'GET_DASHBOARD_PERFORMANCE_DATA';
export const DASHBOARD_PERFORMANCE_DATA_SUCCESS =
  'DASHBOARD_PERFORMANCE_DATA_SUCCESS';
export const DASHBOARD_PERFORMANCE_DATA_ERROR =
  'DASHBOARD_PERFORMANCE_DATA_ERROR';

export const GET_COURSE_PERFORMANCE_DATA = 'GET_COURSE_PERFORMANCE_DATA';
export const COURSE_PERFORMANCE_DATA_SUCCESS =
  'COURSE_PERFORMANCE_DATA_SUCCESS';
export const COURSE_PERFORMANCE_DATA_ERROR = 'COURSE_PERFORMANCE_DATA_ERROR';
