export const CLEAR_MY_ORGANIZATION_CASES = 'CLEAR_MY_ORGANIZATION_CASES';
export const MY_ORGANIZATION_CASES = 'MY_ORGANIZATION_CASES';
export const MY_ORGANIZATION_CASES_SUCCESS = 'MY_ORGANIZATION_CASES_SUCCESS';
export const MY_ORGANIZATION_CASES_ERROR = 'MY_ORGANIZATION_CASES_ERROR';

export const CLEAR_CASE = 'CLEAR_CASE';
export const GET_CASE = 'GET_CASE';
export const GET_CASE_SUCCESS = 'GET_CASE_SUCCESS';
export const GET_CASE_ERROR = 'GET_CASE_ERROR';

export const GET_CASE_NOTES = 'GET_CASE_NOTES';
export const GET_CASE_NOTES_SUCCESS = 'GET_CASE_NOTES_SUCCESS';
export const GET_CASE_NOTES_ERROR = 'GET_CASE_NOTES_ERROR';

export const SAVE_CASE_NOTE = 'SAVE_CASE_NOTE';
export const SAVE_CASE_NOTE_SUCCESS = 'SAVE_CASE_NOTE_SUCCESS';
export const SAVE_CASE_NOTE_ERROR = 'SAVE_CASE_NOTE_ERROR';

export const EDIT_CASE_NOTE = 'EDIT_CASE_NOTE';
export const EDIT_CASE_NOTE_SUCCESS = 'EDIT_CASE_NOTE_SUCCESS';
export const EDIT_CASE_NOTE_ERROR = 'EDIT_CASE_NOTE_ERROR';

export const DELETE_CASE_NOTE = 'DELETE_CASE_NOTE';
export const DELETE_CASE_NOTE_SUCCESS = 'DELETE_CASE_NOTE_SUCCESS';
export const DELETE_CASE_NOTE_ERROR = 'DELETE_CASE_NOTE_ERROR';

export const CLEAR_CLONE_PROJECT = 'CLEAR_CLONE_PROJECT';
export const CLONE_PROJECT = 'CLONE_PROJECT';
export const CLONE_PROJECT_SUCCESS = 'CLONE_PROJECT_SUCCESS';
export const CLONE_PROJECT_ERROR = 'CLONE_PROJECT_ERROR';

// export const CLEAR_CLONE_PROJECT = 'CLEAR_CLONE_PROJECT';
export const CREATE_PROJECT = 'CLONE_PROJECT';
export const CREATE_PROJECT_SUCCESS = 'CLONE_PROJECT_SUCCESS';
export const CREATE_PROJECT_ERROR = 'CLONE_PROJECT_ERROR';

export const FETCH_CASE_CATEGORIES_REQUESTED =
  'FETCH_CASE_CATEGORIES_REQUESTED';
export const FETCH_CASE_CATEGORIES_SUCCEEDED =
  'FETCH_CASE_CATEGORIES_SUCCEEDED';
export const FETCH_CASE_CATEGORIES_FAILED = 'FETCH_CASE_CATEGORIES_FAILED';
