export const SET_CALENDAR_SELECTED = 'SET_CALENDAR_SELECTED';
export const SET_CALENDAR_FILTER = 'SET_CALENDAR_FILTER';
export const SET_CALENDAR_SEARCH_FILTER = 'SET_CALENDAR_SEARCH_FILTER';
export const SET_CALENDAR_POPPER = 'SET_CALENDAR_POPPER';

export const GET_CALENDAR_EVENTS = 'GET_CALENDAR_EVENTS';
export const CALENDAR_EVENTS_SUCCESS = 'CALENDAR_EVENTS_SUCCESS';
export const CALENDAR_EVENTS_ERROR = 'CALENDAR_EVENTS_ERROR';

export const GET_CALENDAR_SEARCH_EVENTS = 'GET_CALENDAR_SEARCH_EVENTS';
export const CALENDAR_SEARCH_EVENTS_SUCCESS = 'CALENDAR_SEARCH_EVENTS_SUCCESS';
export const CALENDAR_SEARCH_EVENTS_ERROR = 'CALENDAR_SEARCH_EVENTS_ERROR';

export const CLEAR_CALENDAR_SEARCH_EVENTS = 'CLEAR_CALENDAR_SEARCH_EVENTS';

export const GET_EVENT_DETAILS = 'GET_EVENT_DETAILS';
export const EVENT_DETAILS_SUCCESS = 'EVENT_DETAILS_SUCCESS';
export const EVENT_DETAILS_ERROR = 'EVENT_DETAILS_ERROR';

export const GET_TIMEZONES = 'GET_TIMEZONES';
export const TIMEZONES_SUCCESS = 'TIMEZONES_SUCCESS';
export const TIMEZONES_ERROR = 'TIMEZONES_ERROR';

export const GET_CREATE_EVENT = 'GET_CREATE_EVENT';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const CREATE_EVENT_ERROR = 'CREATE_EVENT_ERROR';

export const GET_EVENT_COURSES_PROJECTS = 'GET_EVENT_COURSES_PROJECTS';
export const EVENT_COURSES_PROJECTS_SUCCESS = 'EVENT_COURSES_PROJECTS_SUCCESS';
export const EVENT_COURSES_PROJECTS_ERROR = 'EVENT_COURSES_PROJECTS_ERROR';

export const GET_EVENT_USERS = 'GET_EVENT_USERS';
export const EVENT_USERS_SUCCESS = 'EVENT_USERS_SUCCESS';
export const EVENT_USERS_ERROR = 'EVENT_USERS_ERROR';

export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
