export const GET_QUIZ_INSTRUCTIONS = 'GET_QUIZ_INSTRUCTIONS';
export const GET_QUIZ_INSTRUCTIONS_SUCCESS = 'GET_QUIZ_INSTRUCTIONS_SUCCESS';
export const GET_QUIZ_INSTRUCTIONS_ERROR = 'GET_QUIZ_INSTRUCTIONS_ERROR';

export const SET_ACTIVE_QUIZ = 'SET_ACTIVE_QUIZ';
export const SET_MANUAL_ATTEMPTS_UPDATE_REQUIRED = 'SET_MANUAL_ATTEMPTS_UPDATE_REQUIRED';

export const GET_QUIZ_QUESTIONS = 'GET_QUIZ_QUESTIONS';
export const GET_QUIZ_QUESTIONS_SUCCESS = 'GET_QUIZ_QUESTIONS_SUCCESS';
export const GET_QUIZ_QUESTIONS_ERROR = 'GET_QUIZ_QUESTIONS_ERROR';

export const GET_QUIZ_RESULT = 'GET_QUIZ_RESULT';
export const GET_QUIZ_RESULT_SUCCESS = 'GET_QUIZ_RESULT_SUCCESS';
export const GET_QUIZ_RESULT_ERROR = 'GET_QUIZ_RESULT_ERROR';

export const GET_ATTEMPT_DETAILS = 'GET_ATTEMPT_DETAILS';
export const GET_ATTEMPT_DETAILS_SUCCESS = 'GET_ATTEMPT_DETAILS_SUCCESS';
export const GET_ATTEMPT_DETAILS_ERROR = 'GET_ATTEMPT_DETAILS_ERROR';

export const GET_ALL_QUIZ_ATTEMPTS = 'GET_ALL_QUIZ_ATTEMPTS';
export const GET_ALL_QUIZ_ATTEMPTS_SUCCESS = 'GET_ALL_QUIZ_ATTEMPTS_SUCCESS';
export const GET_ALL_QUIZ_ATTEMPTS_ERROR = 'GET_ALL_QUIZ_ATTEMPTS_ERROR';

export const SET_ANSWER_TO_QUESTION = 'SET_ANSWER_TO_QUESTION';

export const SHOW_QUIZ_ANSWERS = 'SHOW_QUIZ_ANSWERS';
export const HIDE_QUIZ_ANSWERS = 'HIDE_QUIZ_ANSWERS';

export const QUIZ_TIMER_START = 'QUIZ_TIMER_START';
export const QUIZ_TIMER_STOP = 'QUIZ_TIMER_STOP';
export const QUIZ_TIMER_TICK = 'QUIZ_TIMER_TICK';

export const REMOVE_ACTIVE_QUIZ = 'REMOVE_ACTIVE_QUIZ';

export const RESET_ACTIVE_QUIZ = 'RESET_ACTIVE_QUIZ';

export const SHOW_QUIZ_RESULT = 'SHOW_QUIZ_RESULT';

export const SET_QUIZ_OVER = 'SET_QUIZ_OVER';
export const SET_ATTEMPT_REFERENCE = 'SET_ATTEMPT_REFERENCE';
export const UPDATE_QUIZ_ATTEMPT = 'UPDATE_QUIZ_ATTEMPT';
