export const GET_DASHBOARD_DISCUSSIONS = 'GET_DASHBOARD_DISCUSSIONS';
export const DASHBOARD_DISCUSSIONS_SUCCESS = 'DASHBOARD_DISCUSSIONS_SUCCESS';
export const DASHBOARD_DISCUSSIONS_ERROR = 'DASHBOARD_DISCUSSIONS_ERROR';

export const GET_COURSE_DISCUSSIONS = 'GET_COURSE_DISCUSSIONS';
export const COURSE_DISCUSSIONS_SUCCESS = 'COURSE_DISCUSSIONS_SUCCESS';
export const COURSE_DISCUSSIONS_ERROR = 'COURSE_DISCUSSIONS_ERROR';

export const SET_DISCUSSION_FILTER = 'SET_DISCUSSION_FILTER';
export const UPDATE_DISCUSSION_PIN = 'UPDATE_DISCUSSION_PIN';
export const SET_DASHBOARD_DISCUSSION_FILTER =
  'SET_DASHBOARD_DISCUSSION_FILTER';
export const CREATE_DISCUSSION_SUCCESS = 'CREATE_DISCUSSION_SUCCESS';
export const CREATE_DISCUSSION_REPLY_SUCCESS =
  'CREATE_DISCUSSION_REPLY_SUCCESS';
export const CREATE_DISCUSSION_COMMENT_SUCCESS =
  'CREATE_DISCUSSION_COMMENT_SUCCESS';

export const GET_DISCUSSION_COURSE_STRUCTURE =
  'GET_DISCUSSION_COURSE_STRUCTURE';
export const DISCUSSION_COURSE_STRUCTURE_SUCCESS =
  'DISCUSSION_COURSE_STRUCTURE_SUCCESS';
export const DISCUSSION_COURSE_STRUCTURE_ERROR =
  'DISCUSSION_COURSE_STRUCTURE_ERROR';

export const GET_DISCUSSION_COMMENTS = 'GET_DISCUSSION_COMMENTS';
export const DISCUSSION_COMMENTS_SUCCESS = 'DISCUSSION_COMMENTS_SUCCESS';
export const DISCUSSION_COMMENTS_ERROR = 'DISCUSSION_COMMENTS_ERROR';
