export const GET_STEPS = 'GET_STEPS';
export const GET_STEPS_SUCCESS = 'GET_STEPS_SUCCESS';
export const GET_STEPS_ERROR = 'GET_STEPS_ERROR';

export const ADD_DATASETS = 'ADD_DATASETS';

export const SET_CURRENT_STEP = 'SET_CURRENT_STEP';
export const SET_PREVIOUS_STEP = 'SET_PREVIOUS_STEP';

export const SET_SECONDARY_STEP_AS_PRIMARY = 'SET_SECONDARY_STEP_AS_PRIMARY';

export const OPEN_FLYOUT_PRIMARY = 'OPEN_FLYOUT_PRIMARY';
export const CLOSE_FLYOUT_PRIMARY = 'CLOSE_FLYOUT_PRIMARY';

export const OPEN_FLYOUT_SECONDARY = 'OPEN_FLYOUT_SECONDARY';
export const CLOSE_FLYOUT_SECONDARY = 'CLOSE_FLYOUT_SECONDARY';

export const UNDO_REQUESTED = 'UNDO_REQUESTED';
export const UNDO_SUCCEEDED = 'UNDO_SUCCEEDED';
export const UNDO_FAILED = 'UNDO_FAILED';

export const REDO_REQUESTED = 'REDO_REQUESTED';
export const REDO_SUCCEEDED = 'REDO_SUCCEEDED';
export const REDO_FAILED = 'REDO_FAILED';

export const RESET_REQUESTED = 'RESET_REQUESTED';
export const RESET_SUCCEEDED = 'RESET_SUCCEEDED';
export const RESET_FAILED = 'RESET_FAILED';

export const ROLLBACK_REQUESTED = 'ROLLBACK_REQUESTED';
export const ROLLBACK_SUCCEEDED = 'ROLLBACK_SUCCEEDED';
export const ROLLBACK_FAILED = 'ROLLBACK_FAILED';

export const FETCH_USER_CODE_REQUESTED = 'FETCH_USER_CODE_REQUESTED';
export const FETCH_USER_CODE_SUCCEEDED = 'FETCH_USER_CODE_SUCCEEDED';
export const FETCH_USER_CODE_FAILED = 'FETCH_USER_CODE_FAILED';

export const FETCH_USER_R_CODE_REQUESTED = 'FETCH_USER_R_CODE_REQUESTED';
export const FETCH_USER_R_CODE_SUCCEEDED = 'FETCH_USER_R_CODE_SUCCEEDED';
export const FETCH_USER_R_CODE_FAILED = 'FETCH_USER_R_CODE_FAILED';

export const FETCH_USER_PYTHON_CODE_REQUESTED =
  'FETCH_USER_PYTHON_CODE_REQUESTED';
export const FETCH_USER_PYTHON_CODE_SUCCEEDED =
  'FETCH_USER_PYTHON_CODE_SUCCEEDED';
export const FETCH_USER_PYTHON_CODE_FAILED = 'FETCH_USER_PYTHON_CODE_FAILED';

export const SET_CURRENT_FLYOUT_TAB = 'SET_CURRENT_FLYOUT_TAB';

export const RESET_STEPS = 'RESET_STEPS';

export const SET_FLYOUT_FULLSCREEN = 'SET_FLYOUT_FULLSCREEN';
export const CLOSE_FLYOUT_FULLSCREEN = 'CLOSE_FLYOUT_FULLSCREEN';

export const FETCH_NOTES_REQUESTED = 'FETCH_NOTES_REQUESTED';
export const FETCH_NOTES_SUCCEEDED = 'FETCH_NOTES_SUCCEEDED';
export const FETCH_NOTES_FAILED = 'FETCH_NOTES_FAILED';

export const FETCH_COMMENTS_REQUESTED = 'FETCH_COMMENTS_REQUESTED';
export const FETCH_COMMENTS_SUCCEEDED = 'FETCH_COMMENTS_SUCCEEDED';
export const FETCH_COMMENTS_FAILED = 'FETCH_COMMENTS_FAILED';

export const NEW_COMMENT_POST_REQUESTED = 'NEW_COMMENT_POST_REQUESTED';
export const NEW_COMMENT_POST_SUCCEEDED = 'NEW_COMMENT_POST_SUCCEEDED';
export const NEW_COMMENT_POST_FAILED = 'NEW_COMMENT_POST_FAILED';

export const NEW_REPLY_POST_REQUESTED = 'NEW_REPLY_POST_REQUESTED';
export const NEW_REPLY_POST_SUCCEEDED = 'NEW_REPLY_POST_SUCCEEDED';
export const NEW_REPLY_POST_FAILED = 'NEW_REPLY_POST_FAILED';

export const COMMENT_DELETE_REQUESTED = 'COMMENT_DELETE_REQUESTED';
export const COMMENT_DELETE_SUCCEEDED = 'COMMENT_DELETE_SUCCEEDED';
export const COMMENT_DELETE_FAILED = 'COMMENT_DELETE_FAILED';

export const REPLY_DELETE_REQUESTED = 'REPLY_DELETE_REQUESTED';
export const REPLY_DELETE_SUCCEEDED = 'REPLY_DELETE_SUCCEEDED';
export const REPLY_DELETE_FAILED = 'REPLY_DELETE_FAILED';

export const RESET_FLYOUTS = 'RESET_FLYOUTS';

export const PREVIOUS_STEP_REQUESTED = 'PREVIOUS_STEP_REQUESTED';
export const PREVIOUS_STEP_SUCCEEDED = 'PREVIOUS_STEP_SUCCEEDED';
export const PREVIOUS_STEP_FAILED = 'PREVIOUS_STEP_FAILED';

export const STEP_EXECUTION_CHECK_REQUESTED = 'STEP_EXECUTION_CHECK_REQUESTED';
export const STEP_EXECUTION_CHECK_SUCCEEDED = 'STEP_EXECUTION_CHECK_SUCCEEDED';
export const STEP_EXECUTION_CHECK_FAILED = 'STEP_EXECUTION_CHECK_FAILED';

export const INITIAL_EXECUTION_CHECK_REQUESTED =
  'INITIAL_EXECUTION_CHECK_REQUESTED';
export const INITIAL_EXECUTION_CHECK_SUCCEEDED =
  'INITIAL_EXECUTION_CHECK_SUCCEEDED';
export const INITIAL_EXECUTION_CHECK_FAILED = 'INITIAL_EXECUTION_CHECK_FAILED';

export const FETCH_RESULTS_ERR0R_REQUESTED = 'FETCH_RESULTS_ERROR_REQUESTED';
export const FETCH_RESULTS_ERROR_SUCCEEDED = 'FETCH_RESULTS_ERROR_SUCCEEDED';
export const FETCH_RESULTS_ERROR_FAILED = 'FETCH_RESULTS_ERROR_FAILED';

export const TOGGLE_OUTPUT_ACCORDION = 'TOGGLE_OUTPUT_ACCORDION';

export const SHOW_STEP_DETAILS = 'SHOW_STEP_DETAILS';
export const HIDE_STEP_DETAILS = 'HIDE_STEP_DETAILS';
export const TOGGLE_FULL_SCREEN = 'TOGGLE_FULL_SCREEN';

export const FETCH_EXPERT_STEPS_REQUESTED = 'FETCH_EXPERT_STEPS_REQUESTED';
export const FETCH_EXPERT_STEPS_SUCCEEDED = 'FETCH_EXPERT_STEPS_SUCCEEDED';
export const FETCH_EXPERT_STEPS_FAILED = 'FETCH_EXPERT_STEPS_FAILED';

export const ADD_EXPERT_STEP_MAPPING = 'ADD_EXPERT_STEP_MAPPING';

export const UPDATE_EXPERT_STEP_MAPPING_MILESTONE =
  'UPDATE_EXPERT_STEP_MAPPING_MILESTONE';

export const FETCH_FUNCTION_DESC_REQUESTED = 'FETCH_FUNCTION_DESC_REQUESTED';
export const FETCH_FUNCTION_DESC_SUCCEEDED = 'FETCH_FUNCTION_DESC_SUCCEEDED';
export const FETCH_FUNCTION_DESC_FAILED = 'FETCH_FUNCTION_DESC_FAILED';

export const KILL_EXECUTION_REQUESTED = 'KILL_EXECUTION_REQUESTED';
export const KILL_EXECUTION_SUCCEEDED = 'KILL_EXECUTION_SUCCEEDED';
export const EXECUTION_KILLED = 'EXECUTION_KILLED';
