export const SHOW_DIALOG = 'SHOW_DIALOG';
export const HIDE_DIALOG = 'HIDE_DIALOG';
export const SET_DIALOG_OPTIONS = 'SET_DIALOG_OPTIONS';
export const SET_DIALOG_PARAMS = 'SET_DIALOG_PARAMS';
export const CLEAR_DIALOG_PARAMS = 'CLEAR_DIALOG_PARAMS';

export const SHOW_FILTERS_DIALOG = 'SHOW_FILTERS_DIALOG';
export const HIDE_FILTERS_DIALOG = 'HIDE_FILTERS_DIALOG';
