export const GET_WORKSPACE_SOLVE = 'GET_WORKSPACE_SOLVE';
export const GET_WORKSPACE_SOLVE_SUCCESS = 'GET_WORKSPACE_SOLVE_SUCCESS';
export const GET_WORKSPACE_SOLVE_ERROR = 'GET_WORKSPACE_SOLVE_ERROR';

export const GET_INTERNAL_SOLVE = 'GET_INTERNAL_SOLVE';
export const GET_INTERNAL_SOLVE_SUCCESS = 'GET_INTERNAL_SOLVE_SUCCESS';
export const GET_INTERNAL_SOLVE_ERROR = 'GET_INTERNAL_SOLVE_ERROR';

export const SET_SCENARIO = 'SET_SCENARIO';
export const CLEAR_SOLVE = 'CLEAR_SOLVE';
