export const SEARCH_DATA = 'SEARCH_DATA';
export const EXPLORE_ALL_DATA = 'EXPLORE_ALL_DATA';
export const EXPLORE_ALL_DATA_SUCCESS = 'EXPLORE_ALL_DATA_SUCCESS';
export const EXPLORE_ALL_DATA_ERROR = 'EXPLORE_ALL_DATA_ERROR';
